### PR TITLE
Upgrade to rustc 83b9deaf2

### PR DESCRIPTION
**Pull request by jdm**
There are still a ton of warnings about zero-sized structs in foreign modules, but it compiles at least.

### CODE REVIEW

**Comment by jdm** [comment]
Fixes #22.

**Comment by jdm** [comment]
The switch to my forks of the dependencies is due to https://github.com/rust-lang/cargo/issues/1866.

**Comment by pcwalton** [comment]
This looks fine. Do you want me to land it as is or do you think the changes to the dependent crates should be "upstreamed" to my repositories?

**Comment by jdm** [comment]
I'll make PRs for all of those.

**Comment by jdm** [comment]
@pcwalton This is using your repositories again.

**Comment by pcwalton** [comment]
Awesome, thanks!

**Pull request merged**
